# Generated by Django 5.2.6 on 2025-09-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('hours_remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=32)),
                ('signal', models.CharField(max_length=32)),
                ('telecom', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField()),
                ('driver_id', models.CharField(blank=True, max_length=32, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField()),
                ('category', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=128)),
                ('by', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=16, unique=True)),
                ('cleaning_slot', models.BooleanField()),
                ('stabling_bay', models.IntegerField()),
                ('mileage_odometer', models.IntegerField()),
                ('mileage_last_service', models.DateField()),
                ('branding', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='api.branding')),
                ('certificates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='api.certificates')),
                ('crew', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='api.crew')),
                ('override', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='api.override')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=32)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='api.train')),
            ],
        ),
    ]
