# Generated by Django 5.2.6 on 2025-09-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('reason', models.CharField(max_length=256)),
                ('override', models.BooleanField()),
                ('violations', models.JSONField(blank=True, default=list)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inductions', to='api.train')),
            ],
        ),
    ]
