# Generated by Django 5.2.6 on 2025-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inductionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='signal',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='stock',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='telecom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
