# Generated by Django 5.2.6 on 2025-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_certificates_signal_alter_certificates_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='depot_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
