# Generated by Django 5.2.6 on 2025-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_train_depot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='stabling_bay',
        ),
        migrations.AddField(
            model_name='branding',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
