# Generated by Django 5.2.6 on 2025-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_train_stabling_bay_branding_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='service_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
